In [4]:
import numpy as np 
import pandas as pd

In [3]:
# vectors 
vector = np.array([1, 2, 3])
print(vector)


[1 2 3]


In [2]:
#list 
list = [1,2,3.0,"ayush","ranjan"]
print(l)

[1, 2, 3.0, 'ayush', 'ranjan']


In [7]:
#matrix 
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix1)
matrix2 = np.array([[1,2,3],[4,5,6]])
print(matrix2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [6]:
#dataframe

lst = ['Ayushh', 'Ranjan', 'Jha', 'Vikas', 
            'Raunak', 'Ranjana', 'Jha']
 

df = pd.DataFrame(lst)
print(df)


         0
0   Ayushh
1   Ranjan
2      Jha
3    Vikas
4   Raunak
5  Ranjana
6      Jha


In [7]:
#factor in r is called category in python 


s = pd.Series(["a","b","c","a"], dtype="category")
print(s)


0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a, b, c]


In [9]:
df = pd.DataFrame({"A": ["a", "b", "c", "a"]})
print(df)

   A
0  a
1  b
2  c
3  a


In [11]:
df["B"] = df["A"].astype('category')
print(df)

   A  B
0  a  a
1  b  b
2  c  c
3  a  a
