In [1]:
import numpy as np
import scipy

In [2]:
from scipy.stats import binom

A Survey found out that 65% of the people are satisfied with their jobs .Suppose we pic 25 people at random what is the probablity that 19 of them are satisfied .



Since outcome can be only 2 and each outcome is independent of each other . Therefore it is best to use binomial distrution to find out the probablity .

here n = 25 
p = .65 
X or k = 19 

In [4]:
binom.pmf(k=19,n=25,p =.65)
# pmf = probablity mass function 

0.09077799859322791

suppose we have to know how if we pic 20 person what is the probality that 4 of less person will be the satisfied one 
let's suppose the probablity is 5% this time 

for this we have to find the cummulative probablity function 


In [6]:
binom.cdf(4,20,0.05)

0.9974260596653477

In [7]:
from scipy.stats import poisson

Suppose 3.2 customer comes to mac-D every 4 minutes .What is the probablity that exactly 5 customer will come in 4 min interval .

In [10]:
poisson.pmf(5,3.2)

0.11397938346351824

In [11]:
poisson.pmf(10,6.4)

0.052790043854115495

In [14]:
# probality that upto 7 customer comes in 4 min interval 

print(1- poisson.cdf(7,3.2))
# poisoon.cdf will give probablity till 7 customer ...to find customer more than that we have to subtract it by 1 

0.01682984174895752


Uniform Distribution 

Suppose to assemble a model it takes 27-39 secs and assembly time is uniformly distributed .What is the probablity that a assembly will take 30 and 35 seconds ? 

In [16]:
 np.arange(27,39,1)


array([27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [17]:
from scipy.stats import uniform

In [21]:
uniform.mean(loc = 27, scale = 12)
# loc is the starting point and scale is difference between first and last point i.e. 38 -27 


33.0

In [27]:
uniform.cdf(np.arange(30,36 ,1) ,loc =27 ,scale =12 )

#this will give the probablity of each time .

array([0.25      , 0.33333333, 0.41666667, 0.5       , 0.58333333,
       0.66666667])

In [29]:
uniform.cdf(np.arange(30,36 ,5) ,loc =27 ,scale =12 )

#this will give the probablity of last 2  time intervals  .
# Subtracting them will give us the probablity that a assembly will 30 take 30 and 35 secs 

array([0.25      , 0.66666667])

In [30]:
uniform.std(loc = 27 , scale =12 )

3.4641016151377544

In [ ]:
Normal Distribution 

In [31]:
from scipy.stats import norm

In [33]:
val,m,sd = 68,65.5,2.5 
# val is the value of X , m is the mean ,and sd is the standard deviation 

In [34]:
norm.cdf(val,m,sd)
# this will give us the probality upto 68 

0.8413447460685429

In [36]:
# Now suppose area is given and we want to know the value of x ....if it is standard normal distribution we want to know the z  value 
norm.ppf(0.95)
#value of z 

1.6448536269514722